server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: "${spring-cloud-server-git-uri}"
          default-label: main
          username: "${spring-cloud-server-git-username}"
          password: "${spring-cloud-server-git-password}"

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
